import assert from "node:assert/strict";
import { mkdtemp, readFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import { parseCsv } from "../shared/csv.mjs";
import {
  CANDIDATE_LEDGER_FILE,
  buildListOfDatesJson,
  createListOfDatesOutputPaths,
  writeCandidateLedger,
  writeListOfDatesArtifacts,
} from "../listofdates/artifacts.mjs";

const generatedAt = "2026-06-08T10:00:00.000Z";

function matterJson() {
  return {
    matter_name: "Example Matter",
    client_name: "Client",
    opposite_party: "Builder",
    matter_type: "Consumer",
    jurisdiction: "India",
    brief_description: "Artifact helper test",
  };
}

function sourceIndex() {
  return new Map([
    ["FILE-0001", {
      file_id: "FILE-0001",
      source_label: "Agreement",
      source_short_label: "Agreement",
      source_path: "00_Inbox/Agreement.pdf",
      label_status: "confirmed",
    }],
  ]);
}

function entries() {
  return [
    {
      date_iso: "2026-05-01",
      date_text: "1 May 2026",
      event: "Agreement was signed.",
      legal_relevance: "Supports the agreement chronology.",
      citation: "FILE-0001 p1.b1",
      event_type: "agreement",
      issue_tags: ["agreement"],
      perspective: "client_favourable",
      source_label: "Agreement",
    },
  ];
}

test("List of Dates artifact helper builds stable output paths", () => {
  const outputPaths = createListOfDatesOutputPaths("/tmp/example-matter", { includeCandidates: true });

  assert.deepEqual(outputPaths, {
    directory: "10_Library",
    candidates: `10_Library/${CANDIDATE_LEDGER_FILE}`,
    json: "10_Library/List of Dates.json",
    csv: "10_Library/List of Dates.csv",
    markdown: "10_Library/List of Dates.md",
  });
});

test("List of Dates artifact helper builds single-pass JSON envelope", () => {
  const payload = buildListOfDatesJson({
    matterJson: matterJson(),
    engineVersion: "create-listofdates-v1-ai",
    generatedAt,
    aiRun: { provider: "openai-direct", model: "gpt-4.1" },
    records: [{ file_id: "FILE-0001" }, { file_id: "FILE-0002" }],
    sourceIndex: sourceIndex(),
    entries: entries(),
  });

  assert.equal(payload.schema_version, "list-of-dates/v1");
  assert.equal(payload.engine_version, "create-listofdates-v1-ai");
  assert.equal(payload.generated_at, generatedAt);
  assert.equal(payload.source_record_count, 2);
  assert.deepEqual(payload.ai_run, { provider: "openai-direct", model: "gpt-4.1" });
  assert.deepEqual(payload.matter, {
    matter_name: "Example Matter",
    client_name: "Client",
    opposite_party: "Builder",
    matter_type: "Consumer",
    jurisdiction: "India",
    brief_description: "Artifact helper test",
  });
  assert.equal(payload.source_snapshot[0].file_id, "FILE-0001");
  assert.equal(payload.entries.length, 1);
  assert.equal(Object.hasOwn(payload, "generation_mode"), false);
});

test("List of Dates artifact helper writes JSON, CSV, and markdown artifacts", async () => {
  const matterRoot = await mkdtemp(path.join(os.tmpdir(), "listofdates-artifacts-"));

  const outputPaths = await writeListOfDatesArtifacts({
    matterRoot,
    matterJson: matterJson(),
    engineVersion: "create-listofdates-v2-two-pass",
    markdownEngineVersion: "create-listofdates-v2-two-pass",
    generatedAt,
    aiRun: { provider: "two-pass", model: "gpt-4.1 -> gpt-5.4" },
    records: [{ file_id: "FILE-0001" }],
    sourceIndex: sourceIndex(),
    entries: entries(),
    includeCandidates: true,
    generationMode: "two_pass",
    candidateLedgerPath: `10_Library/${CANDIDATE_LEDGER_FILE}`,
    pass1AiRun: { provider: "openai-direct", model: "gpt-4.1" },
    pass2AiRun: { provider: "openai-direct", model: "gpt-5.4" },
    validation: { candidate_count: 1, accepted_entries: 1, final_entries: 1, clustered_entries: 0 },
  });

  assert.equal(outputPaths.candidates, `10_Library/${CANDIDATE_LEDGER_FILE}`);

  const jsonOutput = JSON.parse(await readFile(path.join(matterRoot, outputPaths.json), "utf8"));
  assert.equal(jsonOutput.generation_mode, "two_pass");
  assert.equal(jsonOutput.candidate_ledger_path, `10_Library/${CANDIDATE_LEDGER_FILE}`);
  assert.deepEqual(jsonOutput.validation, {
    candidate_count: 1,
    accepted_entries: 1,
    final_entries: 1,
    clustered_entries: 0,
  });

  const csvRows = parseCsv(await readFile(path.join(matterRoot, outputPaths.csv), "utf8"));
  assert.equal(csvRows.length, 1);
  assert.equal(csvRows[0].citation, "FILE-0001 p1.b1");

  const markdown = await readFile(path.join(matterRoot, outputPaths.markdown), "utf8");
  assert.match(markdown, /Generated by create-listofdates-v2-two-pass/);
  assert.match(markdown, /Agreement was signed/);
});

test("List of Dates artifact helper writes the candidate ledger file", async () => {
  const matterRoot = await mkdtemp(path.join(os.tmpdir(), "listofdates-candidates-"));

  const outputPath = await writeCandidateLedger(matterRoot, {
    schema_version: "list-of-dates-candidates/v1",
    status: "pass1_complete",
    candidates: [{ candidate_id: "cand_0001" }],
  });

  assert.equal(outputPath, `10_Library/${CANDIDATE_LEDGER_FILE}`);
  const ledger = JSON.parse(await readFile(path.join(matterRoot, outputPath), "utf8"));
  assert.deepEqual(ledger, {
    schema_version: "list-of-dates-candidates/v1",
    status: "pass1_complete",
    candidates: [{ candidate_id: "cand_0001" }],
  });
});
