import assert from "node:assert/strict";
import test from "node:test";

import {
  DEFAULT_LIST_OF_DATES_ENGINE_VERSION,
  renderListOfDatesMarkdown,
} from "../listofdates/rendering.mjs";
import { renderListOfDatesMarkdown as renderFromEngine } from "../create-listofdates-engine.mjs";

test("List of Dates rendering remains available through the engine export", () => {
  assert.equal(renderFromEngine, renderListOfDatesMarkdown);
});

test("List of Dates rendering escapes markdown table cells", () => {
  const markdown = renderListOfDatesMarkdown(
    { matter_name: "Example Matter" },
    [
      {
        date_iso: "2026-05-01",
        event: "Client paid | disputed amount",
        legal_relevance: "Supports | payment chronology",
        source_label: "Order | 1",
      },
    ],
  );

  assert.match(markdown, new RegExp(`Generated by ${DEFAULT_LIST_OF_DATES_ENGINE_VERSION}`));
  assert.match(markdown, /Client paid \\\| disputed amount/);
  assert.match(markdown, /Supports \\\| payment chronology/);
  assert.match(markdown, /Order \\\| 1/);
});

test("List of Dates rendering prefers readable source labels over raw source paths", () => {
  const markdown = renderListOfDatesMarkdown(
    { matter_name: "Example Matter" },
    [
      {
        date_iso: "2026-05-02",
        event: "Notice sent",
        legal_relevance: "Starts response chronology",
        supporting_sources: [
          { source_label: "Demand Notice" },
          { source_path: "10_Library/FILE-0001__Scanned Notice.pdf" },
          { source_short_label: "Email Chain" },
        ],
      },
    ],
  );

  assert.match(markdown, /Demand Notice<br>Scanned Notice\.pdf<br>Email Chain/);
  assert.doesNotMatch(markdown, /FILE-0001__/);
});
