import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import ts from "typescript";

const reactFilePreviewPath = new URL("../react-ui/src/lib/filePreview.ts", import.meta.url);
const reactSourceLabelsPath = new URL("../react-ui/src/lib/sourceLabels.ts", import.meta.url);
const reactActivityPagePath = new URL("../react-ui/src/views/ActivityPage.tsx", import.meta.url);
const reactWorkspaceTreePath = new URL("../react-ui/src/components/workspace/WorkspaceTree.tsx", import.meta.url);
const reactMainContentPath = new URL("../react-ui/src/components/layout/MainContent.tsx", import.meta.url);

async function importReactFilePreviewModule() {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "react-file-preview-test-"));
  const sourceLabels = await readFile(reactSourceLabelsPath, "utf8");
  const source = await readFile(reactFilePreviewPath, "utf8");
  await writeFile(path.join(tempDir, "sourceLabels.mjs"), transpileReactModule(sourceLabels));
  await writeFile(
    path.join(tempDir, "filePreview.mjs"),
    transpileReactModule(source).replace("from './sourceLabels';", "from './sourceLabels.mjs';"),
  );
  return import(`${pathToFileURL(path.join(tempDir, "filePreview.mjs")).href}?t=${Date.now()}`);
}

function transpileReactModule(source) {
  return ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.ES2020, target: ts.ScriptTarget.ES2020 },
  }).outputText;
}

test("React file preview helper loads text content before rendering preview", async () => {
  const { filePreviewTitle, loadTextFilePreview } = await importReactFilePreviewModule();
  const preview = await loadTextFilePreview("20_Workshop/Party and Officer Map.md", async (path) => {
    assert.equal(path, "20_Workshop/Party and Officer Map.md");
    return { content: "# Party and Officer Map", ext: "md" };
  });

  assert.deepEqual(preview, {
    path: "20_Workshop/Party and Officer Map.md",
    type: "text",
    content: "# Party and Officer Map",
    ext: "md",
  });
  assert.equal(filePreviewTitle("20_Workshop/Party and Officer Map.md"), "Party and Officer Map.md");
});

test("React List of Dates markdown parser preserves source fragments and hides technical citation names", async () => {
  const {
    isListOfDatesMarkdownPath,
    lawyerFacingListOfDatesSourceFragment,
    listOfDatesRelevanceTone,
    parseListOfDatesMarkdown,
    sourceFragmentsForListOfDates,
  } = await importReactFilePreviewModule();

  const parsed = parseListOfDatesMarkdown(`# List of Dates

Matter: Ayesha Vs Japan Airlines

Generated by create-listofdates-v1-ai. Review before relying on this chronology.

| Date | Event | Legal Relevance | Source |
|---|---|---|---|
| 2026-03-10 | Client was denied boarding after showing rule A\\|B | Key incident | S3, S5 |
| 2026-03-13 | Airline sent official confirmation | Official confirmation | Airline email (FILE-0001 p1.b1)<br>FILE-0002 p2.b1 |
`);

  assert.equal(isListOfDatesMarkdownPath("10_Library/Case Timeline.md"), true);
  assert.equal(parsed.title, "List of Dates");
  assert.equal(parsed.matter, "Ayesha Vs Japan Airlines");
  assert.equal(parsed.entries.length, 2);
  assert.equal(parsed.entries[0].event, "Client was denied boarding after showing rule A|B");
  assert.deepEqual(sourceFragmentsForListOfDates(parsed.entries[0].source), ["S3", "S5"]);
  assert.equal(parsed.sourceCount, 4);
  assert.equal(parsed.dateRange, "2026-03-10 to 2026-03-13");
  assert.equal(listOfDatesRelevanceTone(parsed.entries[0].relevance), "attention");
  assert.equal(listOfDatesRelevanceTone(parsed.entries[1].relevance), "official");
  assert.equal(lawyerFacingListOfDatesSourceFragment(parsed.entries[1].source.split("\n")[0]), "Airline email (page 1)");
  assert.equal(lawyerFacingListOfDatesSourceFragment(parsed.entries[1].source.split("\n")[1]), "Source label unavailable (page 2)");
});

test("React Activity output action fetches preview content before opening file view", async () => {
  const source = await readFile(reactActivityPagePath, "utf8");
  assert.match(source, /const preview = await loadTextFilePreview\(outputPath,\s*\(path\) => api\.getFile\(path, matterName\)\)/);
  assert.match(source, /if \(activeMatterNameRef\.current !== matterName\) return;\s*dispatch\(\{ type: 'SET_ACTIVE_FILE'/);
  assert.match(source, /payload: preview/);
  assert.doesNotMatch(source, /SET_FILE_PREVIEW', payload: \{ path: outputPath, type: 'text' \}/);
});

test("React file preview renders List of Dates markdown as chronology instead of raw preformatted text", async () => {
  const source = await readFile(new URL("../react-ui/src/components/layout/MainContent.tsx", import.meta.url), "utf8");

  assert.match(source, /isListOfDatesMarkdownPath\(preview\.path\)/);
  assert.match(source, /parseListOfDatesMarkdown\(preview\.content \|\| ''\)/);
  assert.match(source, /<ListOfDatesMarkdownPreview parsed=\{listOfDates\} \/>/);
  assert.match(source, /Copy Markdown/);
  assert.match(source, /chronology-table/);
  assert.match(source, /lawyerFacingListOfDatesSourceFragment\(fragment\)/);
});

test("React file preview exposes non-destructive source removal confirmation", async () => {
  const source = await readFile(reactMainContentPath, "utf8");
  const client = await readFile(new URL("../react-ui/src/api/client.ts", import.meta.url), "utf8");
  const styles = await readFile(new URL("../react-ui/src/styles/global.css", import.meta.url), "utf8");

  assert.match(source, /sourceFileIdForPreviewPath\(preview\.path\)/);
  assert.match(source, /Remove from active record/);
  assert.match(source, /source bytes and history were preserved/i);
  assert.match(source, /api\.getSourceRemovalImpactPreview/);
  assert.match(source, /api\.removeSourceFromActiveRecord/);
  assert.match(source, /Reason required/);
  assert.match(client, /\/api\/source-removal\/remove-from-active-record/);
  assert.match(styles, /source-removal-panel/);
});

test("React Workspace tree ignores late text previews after matter changes", async () => {
  const source = await readFile(reactWorkspaceTreePath, "utf8");

  assert.match(source, /const activeMatterNameRef = useLatestValue\(state\.activeMatter\?\.name \?\? null\)/);
  assert.match(source, /const matterName = state\.activeMatter\?\.name \?\? null/);
  assert.match(source, /api\.getFileRawUrl\(path, matterName \?\? undefined\)/);
  assert.match(source, /const preview = await loadTextFilePreview\(path,\s*\(filePath\) => api\.getFile\(filePath, matterName \?\? undefined\)\)/);
  assert.match(source, /if \(activeMatterNameRef\.current !== matterName\) return;\s*dispatch\(\{ type: 'SET_FILE_PREVIEW', payload: preview \}\)/);
  assert.match(source, /catch \(e\) \{\s*if \(activeMatterNameRef\.current !== matterName\) return;/);
});

test("React workspace adapter preserves backend preview metadata", async () => {
  const source = await readFile(new URL("../react-ui/src/api/client.ts", import.meta.url), "utf8");
  const types = await readFile(new URL("../react-ui/src/types/index.ts", import.meta.url), "utf8");

  assert.match(types, /previewable\?: boolean/);
  assert.match(types, /previewKind\?: string/);
  assert.match(source, /previewable: node\.previewable/);
  assert.match(source, /previewKind: node\.previewKind/);
});

test("React Workspace tree respects backend preview kind before fetching text", async () => {
  const source = await readFile(reactWorkspaceTreePath, "utf8");

  assert.match(source, /file\.previewKind === 'text'/);
  assert.match(source, /file\.previewable === false/);
  assert.match(source, /type: file\.previewKind === 'pdf' \? 'pdf' : 'image'/);
  assert.doesNotMatch(source, /const isPdf = ext\?\.toLowerCase\(\) === 'pdf'/);
});
