import type { FilePreview } from '../types';
import { lawyerFacingSourceLabel } from './sourceLabels';

export type ReadTextFilePreview = (path: string) => Promise<{ content: string; ext: string }>;

export interface ListOfDatesMarkdownEntry {
  date: string;
  event: string;
  relevance: string;
  source: string;
}

export interface ParsedListOfDatesMarkdown {
  title: string;
  matter: string;
  generated: string;
  entries: ListOfDatesMarkdownEntry[];
  sourceCount: number;
  dateRange: string;
}

export async function loadTextFilePreview(
  path: string,
  readTextFile: ReadTextFilePreview,
): Promise<FilePreview> {
  const result = await readTextFile(path);
  return { path, type: 'text', content: result.content, ext: result.ext };
}

export function filePreviewTitle(path: string): string {
  return path.split('/').pop() || path;
}

export function isListOfDatesMarkdownPath(path: string): boolean {
  return normalizedPath(path) === '10_library/list of dates.md';
}

export function parseListOfDatesMarkdown(markdown = ''): ParsedListOfDatesMarkdown {
  const text = String(markdown || '');
  const lines = text.split(/\r?\n/);
  const title = (lines.find((line) => /^#\s+/.test(line)) || '# Case Timeline').replace(/^#\s+/, '').trim();
  const matter = extractMetadataLine(lines, 'Matter');
  const generated = lines.find((line) => /^Generated by\s+/i.test(line))?.trim() || '';
  const headerIndex = lines.findIndex((line) => /\|\s*Date\s*\|\s*Event\s*\|\s*Legal Relevance\s*\|\s*Source\s*\|/i.test(line));

  if (headerIndex === -1) {
    return { title, matter, generated, entries: [], sourceCount: 0, dateRange: '' };
  }

  const entries: ListOfDatesMarkdownEntry[] = [];
  for (const line of lines.slice(headerIndex + 2)) {
    if (!line.trim().startsWith('|')) break;
    const cells = splitMarkdownTableRow(line);
    if (cells.length < 4) continue;
    entries.push({
      date: normalizeMarkdownCell(cells[0]),
      event: normalizeMarkdownCell(cells[1]),
      relevance: normalizeMarkdownCell(cells[2]),
      source: normalizeSourceCell(cells[3]),
    });
  }

  const sourceCount = countUniqueSources(entries);
  const dates = entries.map((entry) => entry.date).filter(Boolean);
  const dateRange = dates.length ? `${dates[0]} to ${dates[dates.length - 1]}` : '';
  return { title, matter, generated, entries, sourceCount, dateRange };
}

export function sourceFragmentsForListOfDates(source = ''): string[] {
  const normalized = String(source || '').replace(/<br\s*\/?>/gi, '\n');
  const firstPass = normalized.split(/\n+/).map((item) => item.trim()).filter(Boolean);
  const fragments = firstPass.length ? firstPass : [normalized.trim()].filter(Boolean);
  return fragments.flatMap((fragment) => {
    if (/^S\d+(,\s*S\d+)*$/i.test(fragment)) return fragment.split(/\s*,\s*/);
    return [fragment];
  }).filter(Boolean);
}

export function lawyerFacingListOfDatesSourceFragment(fragment = ''): string {
  return lawyerFacingSourceLabel({
    label: fragment,
    citation: fragment,
    fallback: 'Source label unavailable',
  });
}

export function listOfDatesRelevanceTone(relevance = ''): 'attention' | 'official' | 'record' | 'neutral' {
  const normalized = String(relevance || '').toLowerCase();
  if (/(key incident|financial damage|denied boarding|refused|compelled|damage|dispute)/.test(normalized)) return 'attention';
  if (/(official|confirmation|confirmed|consulate)/.test(normalized)) return 'official';
  if (/(payment|flight|record|invoice|ledger|immigration)/.test(normalized)) return 'record';
  return 'neutral';
}

function extractMetadataLine(lines: string[], label: string): string {
  const pattern = new RegExp(`^${label}:\\s*(.+)$`, 'i');
  const line = lines.find((candidate) => pattern.test(candidate));
  return line ? (line.match(pattern)?.[1] || '').trim() : '';
}

function splitMarkdownTableRow(line = ''): string[] {
  const trimmed = String(line || '').trim().replace(/^\|/, '').replace(/\|$/, '');
  const cells: string[] = [];
  let current = '';
  for (let index = 0; index < trimmed.length; index += 1) {
    const char = trimmed[index];
    if (char === '\\' && trimmed[index + 1] === '|') {
      current += '|';
      index += 1;
      continue;
    }
    if (char === '|') {
      cells.push(current.trim());
      current = '';
      continue;
    }
    current += char;
  }
  cells.push(current.trim());
  return cells;
}

function normalizeMarkdownCell(value = ''): string {
  return String(value || '')
    .replace(/\\\|/g, '|')
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function normalizeSourceCell(value = ''): string {
  return String(value || '')
    .replace(/\\\|/g, '|')
    .replace(/<br\s*\/?>/gi, '\n')
    .split(/\n+/)
    .map((item) => item.replace(/\s+/g, ' ').trim())
    .filter(Boolean)
    .join('\n');
}

function countUniqueSources(entries: ListOfDatesMarkdownEntry[]): number {
  const sources = new Set<string>();
  for (const entry of entries) {
    for (const source of sourceFragmentsForListOfDates(entry.source)) {
      const fileIds = source.match(/FILE-\d+/gi) || [];
      if (fileIds.length) {
        fileIds.forEach((fileId) => sources.add(fileId.toUpperCase()));
      } else {
        sources.add(source);
      }
    }
  }
  return sources.size;
}

function normalizedPath(path = ''): string {
  return String(path || '').replace(/\\/g, '/').toLowerCase();
}
