import path from "node:path";

export const DEFAULT_LIST_OF_DATES_ENGINE_VERSION = "create-listofdates-v1-ai";

export function renderListOfDatesMarkdown(
  matterJson,
  entries,
  engineVersion = DEFAULT_LIST_OF_DATES_ENGINE_VERSION,
) {
  const rows = entries.map((entry) => (
    `| ${escapeMarkdownCell(entry.date_iso)} | ${escapeMarkdownCell(entry.event)} | ${escapeMarkdownCell(entry.legal_relevance)} | ${escapeMarkdownCell(formatSourceForDisplay(entry))} |`
  ));
  return `# List of Dates\n\nMatter: ${matterJson.matter_name || "Matter"}\n\nGenerated by ${engineVersion}. Review before relying on this chronology.\n\n| Date | Event | Legal Relevance | Source |\n|---|---|---|---|\n${rows.join("\n")}\n`;
}

function formatSourceForDisplay(entry) {
  const sources = Array.isArray(entry.supporting_sources) && entry.supporting_sources.length
    ? entry.supporting_sources
    : [entry];
  const labels = [];
  const seen = new Set();
  for (const source of sources) {
    const label = formatSupportingSourceForDisplay(source);
    const key = label.toLowerCase();
    if (!label || seen.has(key)) continue;
    seen.add(key);
    labels.push(label);
  }
  return labels.length ? labels.join("<br>") : "Unlabeled source";
}

function formatSupportingSourceForDisplay(source) {
  return source.source_label
    || source.source_short_label
    || source.original_name
    || readableSourcePath(source.source_path)
    || "Unlabeled source";
}

function readableSourcePath(sourcePath = "") {
  const name = path.basename(String(sourcePath || ""));
  return name
    .replace(/^FILE-\d{4,}__/i, "")
    .replace(/\s+/g, " ")
    .trim();
}

function escapeMarkdownCell(value) {
  return String(value ?? "")
    .replace(/\|/g, "\\|")
    .replace(/\s+/g, " ")
    .trim();
}
